### ISSUE TITLE
Where can I download the BikePerson dataset?

### ISSUE THREAD

**Issue by lotus824** [Unakar/Bike-REID#1]
Your project is awesome, I want to reproduce it. But I can't find download link of the BikePerson dataset on the website. Where can I download the BikePerson dataset?

**Comment by Unakar** [comment]
https://drive.google.com/file/d/1u6906LTa2xU4fibwfqkT6cEn81fjOFJa/view

https://pan.baidu.com/s/1FsDna0dCjFDIk8n4a8zRnQ

**Comment by lotus824** [comment]
Thank you for providing the download link!
